name: Generate Changelog

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Prepare changelog branch
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore(changelog): automatic changelog upadate"
          git push HEAD:chore/changelog -f

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: chore/changelog
          title: "chore(changelog): automatic update"
          body: "This PR contains changelog update for the latest release."
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          labels: changelog
          delete-branch: true
